controllers/PostController.php
<?php
namespace app_ta_nanda\controllers;

use Yii;
use technosmart\yii\web\Controller;
use technosmart\models\Post;
use technosmart\models\PostCategory;

class PostController extends Controller
{
    public function actionIndex($id = null, $code = null)
    {
        if (isset($code)) {
            return $this->render($code);
        }
        
        if (isset($id)) {
            $model['post'] = $this->findModel($id);
            $model['posts'] = Post::find()->orderBy(['id' => SORT_DESC])->where(['<>', 'id', $id])->all();
            return $this->render('one', [
                'model' => $model,
                'title' => 'Detail of Post ' . $model['post']->id,
            ]);
        }
    }

    public function actionCategory($id)
    {
        $model['postCategory'] = PostCategory::find()->where(['id' => $id])->one();
        $model['post'] = Post::find()->where(['id_post_category' => $id])->all();
        return $this->render('list', [
            'title' => 'List of Posts',
            'model' => $model,
        ]);
    }

    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SiteController.php
<?php
namespace app_ta_nanda\controllers;

use Yii;
use technosmart\controllers\SiteController as SiteControl;
use app_ta_nanda\models\UserIdentity;
use app_ta_nanda_admin\models\Customer;
use technosmart\models\Post;

class SiteController extends SiteControl
{
    public function behaviors()
    {
        return [
            'access' => $this->access([
                [['index', 'register', 'login', 'error'], true, ['?', '@'], ['GET', 'POST']],
                [['logout'], true, ['@'], ['POST']],
            ]),
        ];
    }

    public function actionIndex()
    {
        // $this->layout = 'main-blog';
        // return $this->render('index-blog');
        $model['posts'] = Post::find()->orderBy(['id' => SORT_DESC])->all();
        
        return $this->render('index', [
            'model' => $model,
        ]);
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        if ( !Yii::$app->request->isPost || !($model['userIdentity'] = UserIdentity::findByLogin(Yii::$app->request->post()['UserIdentity']['login'])) )
            $model['userIdentity'] = new UserIdentity();
        $model['userIdentity']->scenario = 'login';

        if ($model['userIdentity']->load(Yii::$app->request->post()) && $model['userIdentity']->login()) {
            return $this->goBack();
        } else {
            $this->layout = 'empty';
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionRegister()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $render = false;

        $model['userIdentity'] = new UserIdentity();
        $model['userIdentity']->scenario = 'pass';
        $model['customer'] = new Customer();

        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();

            $model['userIdentity']->load($post);
            $model['customer']->load($post);

            if (Yii::$app->request->isAjax && isset($post['ajax'])) {
                $result = array_merge(
                    ActiveForm::validate($model['userIdentity']),
                    ActiveForm::validate($model['customer'])
                );
                return $this->json($result);
            }

            $transaction['userIdentity'] = UserIdentity::getDb()->beginTransaction();
            $transaction['customer'] = Customer::getDb()->beginTransaction();

            try {
                if (!$model['userIdentity']->save()) {
                    throw new \yii\base\UserException('Data tidak berhasil disimpan. Harap lakukan pengisian data kembali.');
                }

                $model['customer']->id = $model['userIdentity']->id;
                $model['customer']->email = $model['userIdentity']->email;
                if (!$model['customer']->save()) {
                    throw new \yii\base\UserException('Data tidak berhasil disimpan. Harap lakukan pengisian data kembali.');
                }
                
                $transaction['userIdentity']->commit();
                $transaction['customer']->commit();
            } catch (\Exception $e) {
                $render = true;
                $transaction['userIdentity']->rollBack();
                $transaction['customer']->rollBack();
            } catch (\Throwable $e) {
                $render = true;
                $transaction['userIdentity']->rollBack();
                $transaction['customer']->rollBack();
            }
        } else {
            $render = true;
        }

        if ($render) {
            $this->layout = 'empty';
            return $this->render('register', [
                'model' => $model,
            ]);
        }
        else {
            Yii::$app->session->setFlash('success', 'Registrasi berhasil. Silahkan login.');
            return $this->goBack();
        }
    }
}

views/site/contact-us.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

if (isset($title)) $this->title = $title;
if (isset($subtitle)) $this->subtitle = $subtitle;
if (isset($breadcrumbs)) $this->params['breadcrumbs'] = $breadcrumbs;

$error = false;
$errorMessage = '';
if ($model['contact_us']->hasErrors()) {
    $error = true; 
    $errorMessage .= Html::errorSummary($model['contact_us'], ['class' => '']);
}
?>

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="padding-y-30 margin-bottom-20">
                <span class="fs-26 padding-y-10 padding-right-20 border-bottom">Contact Us</span>
            </div>

            <?php $form = ActiveForm::begin(['enableClientValidation' => true, 'options' => ['id' => 'app']]); ?>

            <?php if ($error) : ?>
                <div class="alert alert-danger">
                    <?= $errorMessage ?>
                </div>
            <?php endif; ?>

            <div class="box box-break-sm">
                <div class="box-6 m-padding-0 padding-left-0">
                    <?= $form->field($model['contact_us'], 'name')->begin(); ?>
                        <?= Html::activeLabel($model['contact_us'], 'name', ['class' => 'control-label']); ?>
                        <?= Html::activeTextInput($model['contact_us'], 'name', ['class' => 'form-control', 'maxlength' => true]) ?>
                        <?= Html::error($model['contact_us'], 'name', ['class' => 'help-block']); ?>
                    <?= $form->field($model['contact_us'], 'name')->end(); ?>
                </div>

                <div class="box-6 m-padding-0 padding-right-0">
                    <?= $form->field($model['contact_us'], 'email')->begin(); ?>
                        <?= Html::activeLabel($model['contact_us'], 'email', ['class' => 'control-label']); ?>
                        <?= Html::activeTextInput($model['contact_us'], 'email', ['class' => 'form-control', 'maxlength' => true]) ?>
                        <?= Html::error($model['contact_us'], 'email', ['class' => 'help-block']); ?>
                    <?= $form->field($model['contact_us'], 'email')->end(); ?>
                </div>
            </div>

            <?= $form->field($model['contact_us'], 'subject')->begin(); ?>
                <?= Html::activeLabel($model['contact_us'], 'subject', ['class' => 'control-label']); ?>
                <?= Html::activeTextInput($model['contact_us'], 'subject', ['class' => 'form-control', 'maxlength' => true]) ?>
                <?= Html::error($model['contact_us'], 'subject', ['class' => 'help-block']); ?>
            <?= $form->field($model['contact_us'], 'subject')->end(); ?>

            <?= $form->field($model['contact_us'], 'message')->begin(); ?>
                <?= Html::activeLabel($model['contact_us'], 'message', ['class' => 'control-label']); ?>
                <?= Html::activeTextArea($model['contact_us'], 'message', ['class' => 'form-control', 'maxlength' => true]) ?>
                <?= Html::error($model['contact_us'], 'message', ['class' => 'help-block']); ?>
            <?= $form->field($model['contact_us'], 'message')->end(); ?>

            <div class="form-group clearfix">
                <?= Html::submitButton('Send', ['class' => 'btn btn-default bg-azure rounded-xs border-azure']) ?>
                <?= Html::resetButton('Reset', ['class' => 'btn btn-default bg-lighter rounded-xs']); ?> 
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
$this->context->layout = 'error';
?>
<div class="margin-top-50 border-light-red bg-lightest rounded-xs" style="max-width: 400px; width: 100%; margin-left: auto; margin-right: auto;">
    <div class="alert alert-danger margin-0">
        <?= nl2br(Html::encode($message)) ?>
    </div>
    <div class="padding-15">
        <div class="margin-bottom-15"> The above error occurred while the Web server was processing your request. </div>
        <div class="margin-bottom-15"> Please contact us if you think this is a server error. Thank you. </div>
        <div><a href="<?= Yii::$app->getRequest()->getBaseUrl() ?>">Back to Home</a></div>
    </div>
</div>

views/site/index-admin.php
<?php

use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Home';
$this->params['breadcrumbs'][] = $this->title;
?>

Blank page

views/site/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Home';
$this->params['breadcrumbs'][] = $this->title;

Yii::$app->params['slider'] = true;
?>

<div class="bg-lighter">
    <div class="container padding-top-30 padding-bottom-50">
        <div class="margin-y-20 text-center fs-30 f-bold text-azure">
            Featured Service
        </div>
        <div class="box box-bream-sm box-space-md">
            <div class="box-4 rounded-xs hover-bg-dark bg-azure padding-x-30 padding-top-30 padding-bottom-20">
                <div class="text-center fs-18 margin-bottom-10">
                    Klinik
                </div>
                <div class="fs-14 margin-bottom-10">
                    Dengan sistem yang handal, kami siap menolong hewan kesayangan Anda, agar tetap sehat.
                </div>
                <div class="text-center fs-38">
                    <i class="fa fa-check-circle"></i>
                </div>
            </div>
            <div class="box-4 rounded-xs hover-bg-dark bg-azure padding-x-30 padding-top-30 padding-bottom-20">
                <div class="text-center fs-18 margin-bottom-10">
                    Pet Shop
                </div>
                <div class="fs-14 margin-bottom-10">
                    Hewan yang menggemaskan perlu asupan gizi terbaik. Dapatkan kualitas makanan terbaik dengan harga yang murah disini.
                </div>
                <div class="text-center fs-38">
                    <i class="fa fa-check-circle"></i>
                </div>
            </div>
            <div class="box-4 rounded-xs hover-bg-dark bg-azure padding-x-30 padding-top-30 padding-bottom-20">
                <div class="text-center fs-18 margin-bottom-10">
                    Grooming
                </div>
                <div class="fs-14 margin-bottom-10">
                    Hewan juga membutuhkan perawatan. Percayakan pada kami yang berpengalaman lebih dari 10 tahun.
                </div>
                <div class="text-center fs-38">
                    <i class="fa fa-check-circle"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="bg-gray">
    <div class="container padding-top-30 padding-bottom-50">
        <div class="margin-y-20 text-center fs-30 f-bold">
            Jam Kerja
        </div>
        <table class="table table-bordered bg-lightest rounded-xs margin-top-30 border-thin border-light text-center">
            <thead>
                <tr class="bg-azure">
                    <th>Monday</th>
                    <th>Tuesday</th>
                    <th>Wednesday</th>
                    <th>Thursday</th>
                    <th>Friday</th>
                    <th>Saturday</th>
                    <th>Sunday</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>8:00 am</td>
                    <td>8:00 am</td>
                    <td>8:00 am</td>
                    <td>8:00 am</td>
                    <td>8:00 am</td>
                    <td>8:00 am</td>
                    <td>Closed</td>
                </tr>
                <tr>
                    <td>7:00 pm</td>
                    <td>7:00 pm</td>
                    <td>7:00 pm</td>
                    <td>7:00 pm</td>
                    <td>6:00 pm</td>
                    <td>2:00 pm</td>
                    <td>Closed</td>
                </tr>
            </tbody>
        </table>
        <div class="margin-top-10 fs-18 text-center">
            For after hours emergencies, please call (402) 597-2911.
        </div>
    </div>
</div>

<div class="bg-lightest">
    <div class="container padding-top-30 padding-bottom-50">
        <div class="margin-y-20 text-center fs-30 f-bold text-azure">
            Testimonial
        </div>
        <div class="box box-bream-sm box-space-md">
            <div class="box-4 rounded-xs hover-darker-10 padding-x-30 padding-top-30 padding-bottom-20">
                <div class="fs-16 f-italic text-center margin-bottom-10">
                    Saya berlangganan di Anugerah Satwa selama 11 tahun terakhir, pegawainya sangat ramah dan ahli dibidangnya, toko selalu bersih. Saya membeli persediaan kucing dari sini dan harganya sangat terjangkau. Anugerah Satwa selalu menjadi pilihan pertama saya. Saya tidak akan pergi ke tempat lain!
                </div>
                <div class="text-center fs-20 text-dark margin-top-30">
                    Eko Prasetyo
                </div>
                <div class="text-center fs-18">
                    Penggemar Kucing.
                </div>
            </div>
            <div class="box-4 rounded-xs hover-darker-10 padding-x-30 padding-top-30 padding-bottom-20">
                <div class="fs-16 f-italic text-center margin-bottom-10">
                    Pegawainya selalu bersedia membantu Anda menemukan produk yang tepat sesuai kebutuhan Anda. Ya, Anda membayar sedikit lebih banyak, tetapi jika Anda pergi ke WalMart, Anda tidak akan mendapatkan bantuan yang Anda inginkan dalam membeli produk. Anak-anak anjing selalu terlihat diurus dengan baik dan bersih. Mereka bahkan akan membiarkan Anda bermain dengan mereka!
                </div>
                <div class="text-center fs-20 text-dark margin-top-30">
                    Ganang Arief
                </div>
                <div class="text-center fs-18">
                    Pecinta Anjing.
                </div>
            </div>
            <div class="box-4 rounded-xs hover-darker-10 padding-x-30 padding-top-30 padding-bottom-20">
                <div class="fs-16 f-italic text-center margin-bottom-10">
                    Halo Mas :) anjing-anjing saya sekarang sehat semua, semuanya aktif bermain :) Saya akan selalu merekomendasikan Anda kepada siapa saja yang saya kenal, hahaha. Sekali lagi terima kasih banyak.
                </div>
                <div class="text-center fs-20 text-dark margin-top-30 hover-text-azure">
                    Fandy Pradana
                </div>
                <div class="text-center fs-18">
                    Pemilik Anjing.
                </div>
            </div>
        </div>
    </div>
</div>

<div class="bg-lighter">
    <div class="container padding-top-30 padding-bottom-50">
        <div class="margin-y-20 text-center fs-30 f-bold text-azure">
            Artikel
        </div>
        <div class="box margin-bottom-30 equal">
        <?php foreach ($model['posts'] as $key => $post) : ?>
            <div class="box-4 padding-left-0 padding-right-20">
                <img src="<?= Yii::$app->getRequest()->getBaseUrl() ?>/img/cover.jpg" class="rounded-xs" style="width: 100%; height: auto;">
                <div class="fs-15 margin-top-10">
                    <?= Html::a($post->title, ['post/index', 'id' => $post->id], ['class' => 'text-grayest ']) ?>
                </div>
                <div class="text-gray fs-12 margin-top-5">
                    by <?= $post->createdBy->name ?> on <?= $post->created_at ?>
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
</div>

views/site/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;

$error = false;
$errorMessage = '';
if ($model['userIdentity']->hasErrors()) {
    $error = true; 
    $errorMessage .= Html::errorSummary($model['userIdentity'], ['class' => '']);
}
?>

<div class="text-center margin-top-60 m-margin-top-30">
    <img src="<?= Yii::$app->getRequest()->getBaseUrl() ?>/img/logo-inverse.png" width="50px;" class="bg-dark-azure shadow circle padding-5">
</div>
<div class="margin-top-20 border-lighter border-thick shadow rounded-xs" style="max-width: 350px; width: 100%; margin-left: auto; margin-right: auto;">
    <div class="clearfix padding-15 border-bottom bg-azure text-center fs-18">
        <span class="f-italic"><?= $this->title ?></span>
    </div>
    <div class="padding-20 bg-lightest">
        <?php $form = ActiveForm::begin(['id' => 'app']); ?>

            <?= $form->field($model['userIdentity'], 'login')->textInput(/*['autofocus' => true]*/) ?>

            <?= $form->field($model['userIdentity'], 'password')->passwordInput() ?>

            <?= $form->field($model['userIdentity'], 'rememberMe')->checkbox() ?>

            <?php if ($error) : ?>
                <div class="alert alert-danger">
                    <?= $errorMessage ?>
                </div>
            <?php endif; ?>

            <div class="form-group">
                <?= Html::submitButton('Login', ['class' => 'btn btn-default bg-azure rounded-xs border-azure']) ?>
            </div>

        <?php ActiveForm::end(); ?>
    </div>
    <div class="bg-lighter padding-y-10">
        <div class="text-center text-azure fs-16"><?= Yii::$app->params['app.name'] ?></div>
        <div class="text-center fs-12 margin-top-2"><?= Yii::$app->params['app.author'] ?> © <?= date('Y') ?></div>
    </div>
</div>

views/site/register.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Register';
$this->params['breadcrumbs'][] = $this->title;

$error = false;
$errorMessage = '';
if ($model['userIdentity']->hasErrors()) {
    $error = true; 
    $errorMessage .= Html::errorSummary($model['userIdentity'], ['class' => '']);
}
?>

<div class="text-center margin-top-60 m-margin-top-30">
    <img src="<?= Yii::$app->getRequest()->getBaseUrl() ?>/img/logo-inverse.png" width="50px;" class="bg-dark-azure shadow circle padding-5">
</div>
<div class="margin-top-20 border-lighter border-thick shadow rounded-xs" style="max-width: 350px; width: 100%; margin-left: auto; margin-right: auto;">
    <div class="clearfix padding-15 border-bottom bg-azure text-center fs-18">
        <span class="f-italic"><?= $this->title ?></span>
    </div>
    <div class="padding-20 bg-lightest">
        <?php $form = ActiveForm::begin(['id' => 'app']); ?>

            <?= $form->field($model['userIdentity'], 'email')->textInput(/*['autofocus' => true]*/) ?>

            <?= $form->field($model['userIdentity'], 'name')->textInput() ?>

            <?= $form->field($model['userIdentity'], 'password')->passwordInput() ?>

            <?php if ($error) : ?>
                <div class="alert alert-danger">
                    <?= $errorMessage ?>
                </div>
            <?php endif; ?>

            <div class="form-group">
                <?= Html::submitButton('Register', ['class' => 'btn btn-default bg-azure rounded-xs border-azure']) ?>
            </div>

        <?php ActiveForm::end(); ?>
    </div>
    <div class="bg-lighter padding-y-10">
        <div class="text-center text-azure fs-16"><?= Yii::$app->params['app.name'] ?></div>
        <div class="text-center fs-12 margin-top-2"><?= Yii::$app->params['app.author'] ?> © <?= date('Y') ?></div>
    </div>
</div>